export enum RuntimeEventType {
  SESSION_STARTED = 'SESSION_STARTED',
  TEMPLATE_CREATED = 'TEMPLATE_CREATED',
  COMMAND_STARTED = 'COMMAND_STARTED',
  COMMAND_STDOUT = 'COMMAND_STDOUT',
  COMMAND_STDERR = 'COMMAND_STDERR',
  COMMAND_COMPLETED = 'COMMAND_COMPLETED',
  DEVSERVER_STARTED = 'DEVSERVER_STARTED',
  PREVIEW_READY = 'PREVIEW_READY',
  SESSION_FAILED = 'SESSION_FAILED',
  SESSION_COMPLETED = 'SESSION_COMPLETED',
}

export interface RuntimeEvent {
  type: RuntimeEventType;
  payload: any;
  timestamp: number;
}
